{% set name = "perpetual" %}
{% set version = "0.7.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/perpetual-{{ version }}.tar.gz
  sha256: b08ab576712b5535fa49fe39e26cff17814bd426f518d9dd24a2f80b82b6177f
  patches:
    - remove-feature-annotations.patch

build:
  skip: true  # [py<39]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.0.0,<1.7.0
    - pip
  run:
    - python
    - numpy
    - typing_extensions

test:
  source_files:
    - scripts
    - python-package
    - resources
  imports:
    - perpetual
  commands:
    - pip check
    - python scripts/make_resources.py
    - chmod +x scripts/run-python-tests.sh  # [not win]
    - scripts/run-python-tests.sh  # [not win]
    - scripts/run-python-tests.ps1  # [win]
  requires:
    - pip
    - pytest
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - maturin
    - pandas
    - black
    - sklearn-compat
    - polars
    - seaborn
    - pyarrow

about:
  home: https://perpetual-ml.com
  dev_url: https://github.com/perpetual-ml/perpetual
  doc_url: https://perpetual-ml.github.io/perpetual/
  summary: A self-generalizing gradient boosting machine which doesn't need hyperparameter optimization
  license: AGPL-3.0-only
  license_file:
    - LICENSE
    - python-package/LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - thewchan
    - deadsoul44
